# -*- coding: utf-8 -*-
"""apiCall

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h9X72iN-d4UnkFj-5GckpudLtBW2z31h
"""

import requests
import pandas as pd
import json

tvShow = 'office'
url = 'https://api.tvmaze.com/singlesearch/shows?q={}'.format(tvShow)
print(url)

response = requests.get(url)

data = response.json()

dfDriverData = pd.json_normalize(data)

print(dfDriverData)